services:
  - type: web
    name: sbtetap-results
    env: node
    buildCommand: |
      npm install
      npx playwright install
    startCommand: npm start
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
